# Comment: This is your state machine

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  DataTransformationPipeline

  PK trying things out

Resources:
  DataTransformationPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./state-machine.yaml
      # DefineSubstitutions:
      #   HandleUserInputFunctionArn: !GetAtt HandleUserInput.Arn
      #   ProcessMessageIntoHashArn: !GetAtt ProcessMessageIntoHash.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HandleUserInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessMessageIntoHash

  HandleUserInputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./HandleUserInput/src/HandleUserInput/
      Handler: HandlerUserInput::HandleUserInput.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256

  ProcessMessageIntoHash:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ProcessMessageIntoHash/src/ProcessMessageIntoHash/
      Handler: ProcessMessageIntoHash::ProcessMessageIntoHash.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256