AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  DataTransformationPipeline

  PK trying things out

Resources:
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Service: 
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "lambda.InvokeFunction"
                Resource: "*"

StartAt: HandleUserInput
States:
  HandleUserInput:
    Type: Task
    Resource: ${HandleUserInputFunctionArn}
    OutputPath: $.Payload
    Parameters:
      FunctionName: arn:aws:lambda:eu-west-2:381665830549:function:PKHandleUserInput
      Payload:
        FirstName: Peter
        Surname: Keenan
        Message: This is a very brief testing message.
    Retry:
      - ErrorEquals:
          - Lambda.ServiceException
          - Lambda.AWSLambdaException
          - Lambda.SdkClientException
        IntervalSeconds: 2
        MaxAttempts: 6
        BackoffRate: 2
    Next: ProcessMessageIntoHash
  ProcessMessageIntoHash:
    Type: Task
    Resource: ${ProcessMessageIntoHashFunctionArn}
    OutputPath: $.Payload
    Parameters:
      Payload.$: $
      FunctionName: arn:aws:lambda:eu-west-2:381665830549:function:PKProcessMessageIntoHash
    Retry:
      - ErrorEquals:
          - Lambda.ServiceException
          - Lambda.AWSLambdaException
          - Lambda.SdkClientException
        IntervalSeconds: 2
        MaxAttempts: 6
        BackoffRate: 2
    End: true


  DataTransformationPipeline:
    Type: AWS::Serverless::StateMachine
    Properties:
      # DefinitionUri: ./state-machine.yaml
      DefinitionSubstitutions:
        HandleUserInputFunctionArn: !GetAtt HandleUserInputFunction.Arn
        ProcessMessageIntoHashFunctionArn: !GetAtt ProcessMessageIntoHashFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HandleUserInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessMessageIntoHashFunction

  HandleUserInputFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: ./HandleUserInput/src/HandleUserInput/
      Handler: HandlerUserInput::HandleUserInput.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256

  ProcessMessageIntoHashFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: ./ProcessMessageIntoHash/src/ProcessMessageIntoHash/
      Handler: ProcessMessageIntoHash::ProcessMessageIntoHash.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256

Outputs:
  DataTransformationPipelineArn:
    Description: "Sample data transformation pipeline ARN"
    Value: !Ref DataTransformationPipeline
  DataTransformationPipelineRoleArn:
    Description: "IAM Role created for Data Transformation state machine"
    Value: !GetAtt DataTransformationPipelineRole.Arn