version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "process-message-into-hash-pk"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nnheboz2idu"
s3_prefix = "process-message-into-hash-pk"
region = "eu-west-2"
profile = "labs"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "pk-try-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nnheboz2idu"
s3_prefix = "pk-try-1"
region = "eu-west-2"
profile = "labs"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
